language: ruby, node_js
node_js:
- "0.12"

rvm:
- 2.2.2
# Assume bundler is being used, install step will run `bundle install`.

before_install: sudo npm install -g grunt-cli

script:
  - npm install
  - grunt build

# branch whitelist
branches:
  only:
  - master     # test the gh-pages branch
  - /feat-(.*)/ # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
