language: ruby
rvm:
- 2.2.2
# Assume bundler is being used, install step will run `bundle install`.
script:
  - bundle exec jekyll build

# branch whitelist
branches:
  only:
  - master     # test the gh-pages branch
  - /feat-(.*)/ # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
