name: "The Open Source Club"
description: ""

url: "http://localhost:4040"

paginate: 10


permalink: pretty
highlighter: true


assets:
  js_compressor:  yui
  css_compressor: yui
  
exclude: [vendor]
