name: "The Open Source Club"
description: "a registered student organization composed of members from all around campus and out into the community who share a common enthusiasm for free, open source software."
url: "opensource.osu.edu"

paginate: 10


permalink: pretty
highlighter: true

assets:
  js_compressor:  uglifier
  css_compressor: sass

jekyll-press:
  exclude: 'sitemap.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options

exclude:
  - "node_modules"
  - "package.json"
  - "bower_components"
  - "bower.json"
  - "Gruntfile.coffee"
