name: "The Open Source Club"
url: "opensource.osu.edu"
baseurl: ''
paginate: 10
description: >
  The Open Source Club at at the Ohio State University is a registered student
  organization composed of members from all around campus and out into the
  community who share a common enthusiasm for free, open source software.

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

permalink: pretty
highlighter: true

exclude:
  - "node_modules"
  - "Gemfile"
  - "Gemfile.lock"
  - "package.json"
  - "bower_components"
  - "bower.json"
  - "Gruntfile.coffee"
  - "init.sh"
  - "_assets"
