name: "The Open Source Club"
description: "a registered student organization composed of members from all around campus and out into the community who share a common enthusiasm for free, open source software."
url: "opensource.osu.edu"
baseurl: open-source-club-website

paginate: 10

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

permalink: pretty
highlighter: true

jekyll-press:
  exclude:
    - "sitemap.xml"
    - "rss.xml"

  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options

exclude:
  - "node_modules"
  - "Gemfile"
  - "Gemfile.lock"
  - "package.json"
  - "bower_components"
  - "bower.json"
  - "Gruntfile.coffee"
  - "init.sh"
