baseURL = "https://opensource.osu.edu/"
languageCode = "en-us"
title = "Open Source Club"
description = "At The Ohio State University"
theme = "kube"

[[menu.main]]
    name = "About"
    url = "/about"

[[menu.main]]
    name = "Events"
    url = "/events"

[params]
    twitter = "osuosc"
    github = "OSUOSC"
