baseURL = "https://opensource.osu.edu/"
languageCode = "en-us"
title = "Open Source Club"
theme = "kube"

[[menu.main]]
    name = "About"
    url = "/about"

[[menu.main]]
    name = "Events"
    url = "/events"
