name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: Hugo to GH Pages
        # You may pin to the exact commit or the version.
        # uses: chabad360/hugo-gh-pages@0bcf754dc6c823a580c58a59a3baa476a41258d3
        uses: chabad360/hugo-gh-pages@v2
        with:
          # A Github Personal Access Token with Repo permissions
          githubToken: ${{ github.token }}
          # The custom domain name for your GH Pages Site
          cname: osuoac.org
          # The branch to push the built site to
          branch: deploy
