name: CI

on:
  push:
    branches: [ new-site ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Hugo
        run: sudo apt update && sudo apt install -y hugo

      - name: Print Version
        run: hugo version

      - name: Build
        run: hugo

      # Deploy to local repo
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: deploy-temp
          FOLDER: public
          SQUASH_HISTORY: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
